Repository ExEr7um/vue3-vscode-snippets, pull requests merged in 2023-12, with the labels that each got.

#58 feat: Add `withDefaults` snippet for `defineProps`
  README.md
  snippets/vue/vue-script.code-snippets
Labels: Feature

#59 feat: Add `ref` with generic type argument
  README.md
  snippets/vue/vue-script.code-snippets
Labels: Feature

#60 docs: Format tables in `README`
  README.md
Labels: Documentation

#61 chore: Update contributors
  package.json
Labels: Chore
